POST http://localhost:5000/react-native-household-app/us-central1/webApi/tasks
Content-Type: application/json

{
    "description": "batman-Man",
    "value": 2
}

###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/tasks/KsagruZdZUhJDJZnAYNS

###

###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/tasks

###