POST http://localhost:5001/react-native-household-app/us-central1/webApi/tasks
Content-Type: application/json

{
    "description": "Hela dagen lång",
    "value": 2,
    "houseHoldId": "1J8rfrvRn6TUE8U9wJnv",
    "repeated": 3,
    "archived": false,
    "name": "Fiska"
}

###
// get all tasks of householdID, send in householdID..
GET http://localhost:5001/react-native-household-app/us-central1/webApi/tasks/1J8rfrvRn6TUE8U9wJnv

###
GET http://localhost:5001/react-native-household-app/us-central1/webApi/tasks/householdtasks/1J8rfrvRn6TUE8U9wJnv

###
###
# GET http://localhost:5000/react-native-household-app/us-central1/webApi/tasks
// dont think we are going to need this..
###
//update, send in id in url and the whole objekt
PUT http://localhost:5000/react-native-household-app/us-central1/webApi/tasks/e23PF2PrNAkQ9YYm7WJE
Content-Type: application/json

{
    "description": "damsuga mattan",
    "value": 2,
    "houseHoldId": "houseHoldId1",
    "repeated": 3,
    "name": "städa"
}

###

###
// delete task on task id
DELETE  http://localhost:5000/react-native-household-app/us-central1/webApi/tasks/mAYLUENps7KWqnKPtI3D

###

###
// arcive task on task id
PATCH http://localhost:5000/react-native-household-app/us-central1/webApi/tasks/vwIqUUMi7kYjBRmqDS7n

###