POST http://192.168.1.240:5001/react-native-household-app/us-central1/webApi/household
Content-Type: application/json

{
    "name": "Foos hushåll",
    "ownerId": "WrHSQTb8vsVQMVRVO14z",
    "member": {
        "name": "username",
        "userId": "WrHSQTb8vsVQMVRVO14z",
        "emoji": 2
    }

}


###
// Join household/inviteCode
post http://localhost:5000/react-native-household-app/us-central1/webApi/household/join
Content-Type: application/json

{
    "houseHoldId": "D66g4HdjydwhJSmDUsWm",
    "inviteCode": "4527",
    "member": {
        "name": "username",
        "userId": "userID som vill jiona",
        "emoji": 1
    }
}


###
// GET 
// get all houseHolds for 1 user on userId param
GET http://localhost:5000/react-native-household-app/us-central1/webApi/household/WrHSQTb8vsVQMVRVO14z

###

###
// GET 
// get a houseHolds on inviteCode param
GET http://localhost:5000/react-native-household-app/us-central1/webApi/household/invitecode/1111

###

//accept user
PATCH http://localhost:5000/react-native-household-app/us-central1/webApi/household/accept
Content-Type: application/json

{
    "houseHoldId": "Dt1nCSiTG5QWYtPuMFQR",
    "userId": "userID soddddm vill jiona"
    
}

###

###

//make user owner
PATCH http://localhost:5000/react-native-household-app/us-central1/webApi/household/owner
Content-Type: application/json

{
    "houseHoldId": "Dt1nCSiTG5QWYtPuMFQR",
    "userId": "userID soddddm vill jiona"
    
}

###
