POST http://localhost:5000/react-native-household-app/us-central1/webApi/household
Content-Type: application/json

{
    "name": "batman-Man 2",
    "ownerId": "userID som skapar",
    "member": {
        "id": "member id",
        "userId": "userID som skapar",
        "emoji": 2
    }

}

###
// Join household/inviteCode, kanske ska vara en post? 
post http://localhost:5000/react-native-household-app/us-central1/webApi/household/join
Content-Type: application/json

{
    "houseHoldId": "Dt1nCSiTG5QWYtPuMFQR",
    "inviteCode": "8855",
    "member": {
        "id": "member id f",
        "userId": "userID som vill jiona",
        "emoji": 1
    }
}

###
// GET 
GET http://localhost:5000/react-native-household-app/us-central1/webApi/household/40Jpw3OVxGURAfJfru9t
