

POST http://localhost:5000/react-native-household-app/us-central1/webApi/member
Content-Type: application/json

{
    "userId": "abc",
    "emoji": 1,
    "email": "foo.com",
    "isOwner": false
}

// skulle kunna ta bort isOwner här, sen när man gör hushåll sätts den till true i själva hushåll istället