POST http://localhost:5000/react-native-household-app/us-central1/webApi/donetask
Content-Type: application/json

{
    "taskId": "DP7D1PnUMtgnGmXSAKRa",
    "userId": "JgvhgCtmZ4ieDM7HvLHE",
    "houseHoldId": "R5w28IABhbyKneznYwBQ",
    "value": 8
}

//dates sätts inne


###
// GET 
GET http://localhost:5001/react-native-household-app/us-central1/webApi/donetask/Re0I6SHot3s88mjFLVUU
