POST http://localhost:5001/react-native-household-app/us-central1/webApi/donetask
Content-Type: application/json

{
    "taskId": "Re0I6SHot3s88mjFLVUU",
    "userId": "userID som vill jiona2",
    "houseHoldId": "1J8rfrvRn6TUE8U9wJnv"
}

//dates sätts inne


###
// GET 
GET http://localhost:5000/react-native-household-app/us-central1/webApi/donetask/40Jpw3OVxGURAfJfru9t
