

POST http://localhost:5000/react-native-household-app/us-central1/webApi/users
Content-Type: application/json

{
    "userName": "batman-Man",
    "email": "f2o9.com",
    "password": "hej"
}



###
post http://172.19.200.32:5001/react-native-household-app/us-central1/webApi/users/signin
Content-Type: application/json

{
    "email": "foo@foo.com",
    "password": "fobarr"
}



###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/users/91aE3WLQugShqq2Xg8hq

###

###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/users

###