

POST http://localhost:5000/react-native-household-app/us-central1/webApi/users
Content-Type: application/json

{
    "userName": "batman",
    "email": "foo@f5o.com",
    "password": "foobar"
}



###
post http://172.19.200.32:5001/react-native-household-app/us-central1/webApi/users/signin
Content-Type: application/json

{
    "email": "foo@f5o.com",
    "password": "foobar"
}



###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/users/91aE3WLQugShqq2Xg8hq

###

###
GET http://localhost:5000/react-native-household-app/us-central1/webApi/users

###