# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            firebase-api/functions/package-lock.json
            household-app/package-lock.json

      - name: Install dependencies household-app
        run: npm ci
        working-directory: household-app

      - name: Install dependencies firebase-api
        run: npm ci
        working-directory: firebase-api/functions

      - name: Run build firebase-api
        run: tsc -b
        working-directory: firebase-api/functions

      - name: Run build household-app
        run: tsc -b
        working-directory: household-app

      - name: Run lint household-app
        run: npm run lint --if-present
        working-directory: household-app

      - name: Run lint firebase-api
        run: npm run lint --if-present
        working-directory: firebase-api/functions
